StatsForeGolfers/ProtoWeb/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProtoWeb.Models
{
    public class User
    {
        public string Name { get; set; }
        public string HomeClub { get; set; }
        public int MemberId { get; set; }
        public double Handicap { get; set; }
        public string Status { get; set; }
        public int CurrentCourseId { get; set; }
        public int CurrentHolesFilled { get; set; }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Users/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Models;

namespace ProtoWeb.Users
{
    public class UserModel : PageModel
    {
        [BindProperty]
        public User UserData { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //return RedirectToPage("/Courses/GetAllCourses");
            return Page();
        }

        public IActionResult OnPostUserCreate()
        {
            UserRepository.Instance.Add(UserData);

            if (UserRepository.Instance.Get() != null)
            {
                Debug.WriteLine(UserRepository.Instance.Get().Name);
                Debug.WriteLine(UserRepository.Instance.Get().HomeClub);
                Debug.WriteLine("User");
            }

            return RedirectToPage("/Courses/SelectCourse");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Users/User.cshtml
@page
@model ProtoWeb.Users.UserModel
@{
    ViewData["Title"] = "User";
}

<!DOCTYPE HTML>
<html lang="en">
<head>
    
</head>
<body>
    <div class="row justify-content-center p-4">
        <div class="col-auto">
            <div class="form-check">
                <div class="container-fluid">
                    <h1 class="text-center">User Info</h1>
                </div>
                <div class="img-fluid text-center p-2">
                    <img src="../img/user_icon.png" height="100" />
                </div>
                <form name="formUser" method="post">
                    <div class="my-auto container frame pl-4 pr-4">
                        <h5 class="text-dark">What is Your Status?</h5>
                        <div style="padding-left: 1.25rem">
                            <input asp-for="@Model.UserData.Status" type="radio" name="Status" class="form-check-input" value="Amateur" />
                            <label asp-for="@Model.UserData.Status" class="control-label">
                                Amateur
                            </label>
                            <span asp-validation-for="@Model.UserData.Status" class="text-danger"></span>

                            <br />

                            <input asp-for="@Model.UserData.Status" type="radio" name="Status" class="form-check-input" value="Intermediate" />
                            <label asp-for="@Model.UserData.Status" class="control-label">
                                Intermediate
                            </label>
                            <span asp-validation-for="@Model.UserData.Status" class="text-danger"></span>

                            <br />

                            <input asp-for="@Model.UserData.Status" type="radio" name="Status" class="form-check-input" value="Pro" />
                            <label asp-for="@Model.UserData.Status" class="control-label">
                                Pro
                            </label>
                            <span asp-validation-for="@Model.UserData.Status" class="text-danger"></span>
                        </div>
                        <br />
                        <h5 class="text-dark">Name</h5>
                        <div style="padding-left: 1.25rem">
                            <input asp-for="@Model.UserData.Name" type="text" name="Name" class="form-check-input textField" value="Name" />
                            <label asp-for="@Model.UserData.Name" class="control-label">
                                Name
                            </label>
                            <span asp-validation-for="@Model.UserData.Name" class="text-danger"></span>
                        </div>
                        <br />
                        <h5 class="text-dark">Home Club</h5>
                        <div style="padding-left: 1.25rem">
                            <input asp-for="@Model.UserData.HomeClub" type="text" name="HomeClub" class="form-check-input textField" value="Home Club" />
                            <label asp-for="@Model.UserData.HomeClub" class="control-label">
                                Home Club
                            </label>
                            <span asp-validation-for="@Model.UserData.HomeClub" class="text-danger"></span>
                        </div>
                        <br />
                        <h5 class="text-dark">Member Id</h5>
                        <div style="padding-left: 1.25rem">
                            <input asp-for="@Model.UserData.MemberId" type="number" name="MemberId" class="form-check-input textField" value="Member Id" />
                            <label asp-for="@Model.UserData.MemberId" class="control-label">
                                Member Id
                            </label>
                            <span asp-validation-for="@Model.UserData.MemberId" class="text-danger"></span>
                        </div>
                        <br />
                        <h5 class="text-dark">HCP</h5>
                        <div style="padding-left: 1.25rem">
                            <input asp-for="@Model.UserData.Handicap" type="number" name="Handicap" class="form-check-input textField" value="HCP" />
                            <label asp-for="@Model.UserData.Handicap" class="control-label">
                                HCP
                            </label>
                            <span asp-validation-for="@Model.UserData.Handicap" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" asp-page-handler="UserCreate" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>