StatsForeGolfers/ProtoWeb/Pages/Courses/CoursesHoles/CreateHoles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses.CoursesHoles
{
    public class CreateHolesModel : PageModel
    {
        [BindProperty]
        public Hole Hole { get; set; }
        public int CurrentCourseId { get; set; }

        private ICourses courses;
        public CreateHolesModel(ICourses repository)
        {
            courses = repository;
        }

        public IActionResult OnGet(int id)
        {
            CurrentCourseId = id;

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            courses.AddHole(Hole, id);

            return RedirectToPage("../GetAllCourses");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/CoursesHoles/DeleteHole.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses.CoursesHoles
{
    public class DeleteHoleModel : PageModel
    {
        private ICourses courses;
        [BindProperty] 
        public Hole Hole { get; set; }
        public int CurrentCourseId { get; set; }

        public DeleteHoleModel(ICourses repository)
        {
            courses = repository;
        }
        
        public IActionResult OnGet(int holeNo,int id)
        {
            Dictionary<int, Hole> holes = courses.AllHoles(id);
            Hole = holes[holeNo];
            CurrentCourseId = id;

            return Page();
        }

        public IActionResult OnPost(Hole hole, int id)
        {
            courses.DeleteHole(hole,id);
            return RedirectToPage("../GetAllCourses");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/CoursesHoles/EditHole.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses.CoursesHoles
{
    public class EditHoleModel : PageModel
    {
        private ICourses courses;
        [BindProperty] 
        public Hole Hole { get; set; }
        public int CurrentCourseId { get; set; }

        public EditHoleModel(ICourses repository)
        {
            courses = repository;
        }
        public IActionResult OnGet(int holeNo, int id)
        {
            Dictionary<int, Hole> holes = courses.AllHoles(id);
            Hole = holes[holeNo];
            CurrentCourseId = id;
            return Page();
        }

        public IActionResult OnPost(Hole hole,int id)
        {
            courses.UpdateHole(hole, id);
            return RedirectToPage("../GetAllCourses");
        }

    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/CoursesHoles/GetAllHoles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses.CoursesHoles
{
    public class GetAllHolesModel : PageModel
    {
       [BindProperty]
        public Course Course { get; set; }
        public int courseId { get; set; }

        private ICourses courses;

        public GetAllHolesModel(ICourses repository)
        {
            courses = repository;
        }
        public Dictionary<int,Hole> Holes { get; private set; }
        
        public void OnGet(int id)
        {
            Holes = courses.AllHoles(id);
            courseId = id;

            Course = courses.GetCourse(id);
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/CreateCourse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses
{
    public class CreateCourseModel : PageModel
    {
       [BindProperty]
        public Course CurrentCourse { get; set; }
        
        public ICourses courses;
       
        public CreateCourseModel(ICourses repository)
        {
            courses = repository;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Dictionary<int, Hole> holes = new Dictionary<int, Hole>();
            CurrentCourse.Holes = holes;
            courses.AddCourse(CurrentCourse);
            

            return RedirectToPage("GetAllCourses");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/DeleteCourse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses
{
    public class DeleteCourseModel : PageModel
    {
        [BindProperty]
        public Course CurrentCourses { get; set; }

        private ICourses courses;

        public DeleteCourseModel(ICourses repository)
        {
            courses = repository;
        }

        public IActionResult OnGet(int id)
        {
            CurrentCourses = courses.GetCourse(id);
            return Page();
        }

        public IActionResult OnPost()
        {
            courses.DeleteCourse(CurrentCourses);
            return RedirectToPage("GetAllCourses");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/EditCourse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses
{
    public class EditCourseModel : PageModel
    {
        [BindProperty]
        public Course CurrentCourse { get; set; }

        private ICourses courses;

        public EditCourseModel(ICourses repository)
        {
            courses = repository;
        }
        public void OnGet(int id)
        {
            CurrentCourse = courses.GetCourse(id);
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            courses.UpdateCourse(CurrentCourse);
            return RedirectToPage("GetAllCourses");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/GetAllCourses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses
{
    public class GetAllCoursesModel : PageModel
    {
        private ICourses courses;

        public GetAllCoursesModel(ICourses repository)
        {
            courses = repository;
        }

        public Dictionary<int, Course> Courses { get; private set; }
        [BindProperty(SupportsGet = true)] public string FilterCriteria { get; set; }

        public IActionResult OnGet()
        {
            Courses = courses.AllCourses();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Courses = courses.FilterCourse(FilterCriteria);
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            Courses = courses.AllCourses();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Courses = courses.FilterCourse(FilterCriteria);
            }
            

            return Page();
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/SelectCourse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Courses
{
    public class SelectCourseModel : PageModel
    {
        private IStatistics statistics;
        private ICourses courses;

        public SelectCourseModel(IStatistics statsRepo, ICourses repository)
        {
            statistics = statsRepo;
            courses = repository;

            // TO CREATE A NEW SHEET EVERY TIME WE START THE PROGRAM.
            statistics.CreateSheet(new StatSheet());
        }

        public Dictionary<int, Course> Courses { get; private set; }
        [BindProperty(SupportsGet = true)] public string FilterCriteria { get; set; }

        public IActionResult OnGet()
        {
            Courses = courses.AllCourses();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Courses = courses.FilterCourse(FilterCriteria);
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            Courses = courses.AllCourses();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Courses = courses.FilterCourse(FilterCriteria);
            }

            return Page();
        }

        public IActionResult OnPostSelectCourse(int id)
        {
            UserRepository.Instance.Get().CurrentCourseId = id;
            UserRepository.Instance.Get().CurrentHolesFilled = 1;

            // If the current holes par is more than 3, we go to the fairway. Otherwise, we skip the fairway shot.
            if (courses.GetCourse(id).Holes[UserRepository.Instance.Get().CurrentHolesFilled].Par > 3)
                return RedirectToPage("/Statistics/InputStats1");
            else
                return RedirectToPage("/Statistics/InputStats2");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Courses/CreateCourse.cshtml
@page
@model ProtoWeb.Pages.Courses.CreateCourseModel
@{
    ViewData["Title"] = "CreateCourse";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1>Create Course</h1>
        <div class="img-fluid text-center">
            <img src="../img/course_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <form method="post">
                @*<input type="hidden" asp-for="@Model.CurrentCourse.Id" />*@
                <div class="form-group">
                    <label asp-for="@Model.CurrentCourse.Id" class="control-label"> Id </label>
                    <input asp-for="@Model.CurrentCourse.Id" class="form-control" />
                    <span asp-validation-for="@Model.CurrentCourse.Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.CurrentCourse.Name" class="control-label">Name </label>
                    <input asp-for="@Model.CurrentCourse.Name" class="form-control" />
                    <span asp-validation-for="@Model.CurrentCourse.Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Courses/DeleteCourse.cshtml
@page "{id}"
@model ProtoWeb.Pages.Courses.DeleteCourseModel
@{
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1>Delete Course</h1>
        <div class="img-fluid text-center">
            <img src="../../img/course_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <h3 class="text-dark">Are you sure you want to delete this Course?</h3>
            <div>
                <form method="post">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CurrentCourses.Id)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CurrentCourses.Id)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CurrentCourses.Name)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CurrentCourses.Name)
                        </dd>

                    </dl>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
                <div class="pt-4">
                    <a class="btn btn-primary" asp-page="GetAllCourses">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Courses/EditCourse.cshtml
@page "{id}"
@model ProtoWeb.Pages.Courses.EditCourseModel
@{
    ViewData["Title"] = "EditCourse";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1>EditCourse</h1>
        <div class="img-fluid text-center">
            <img src="../../img/course_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <form method="post">
                <div class="form-group">
                    <label asp-for="@Model.CurrentCourse.Id" class="control-label"></label>
                    <input asp-for="@Model.CurrentCourse.Id" class="form-control" />
                    <span asp-validation-for="@Model.CurrentCourse.Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.CurrentCourse.Name" class="control-label"></label>
                    <input asp-for="@Model.CurrentCourse.Name" class="form-control" />
                    <span asp-validation-for="@Model.CurrentCourse.Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Courses/GetAllCourses.cshtml
@page
@model ProtoWeb.Pages.Courses.GetAllCoursesModel
@{
    ViewData["Title"] = "GetAllCourses";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1>All Courses</h1>
        <div class="img-fluid text-center">
            <img src="../img/course_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <p>
                <a class="link-dark" asp-page="CreateCourse">Create New Course</a>
            </p>
            <form>
                <p class="text-dark">
                    <input class="textField" type="text" placeholder="Search.." asp-for="FilterCriteria" />
                    <input type="submit" value="Filter" />
                </p>
            </form>
            <table class="table table-striped table-responsive p-3">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Courses)
                    {
                        <tr>
                            <td>
                                <a class="link-dark" asp-page="CoursesHoles/GetAllHoles" asp-route-id="@item.Key"> @item.Value.Name</a>
                            </td>
                            <td>
                                <p>
                                    <a class="link-dark" asp-page="EditCourse" asp-route-id="@item.Key">Edit</a> |
                                    <a class="link-dark" asp-page="DeleteCourse" asp-route-id="@item.Key">Delete</a>
                                </p>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    </div>

StatsForeGolfers/ProtoWeb/Pages/Courses/SelectCourse.cshtml
@page
@model ProtoWeb.Pages.Courses.SelectCourseModel
@{
    ViewData["Title"] = "SelectCourse";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1>Select a Course</h1>
        <div class="img-fluid text-center">
            <img src="../img/course_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <p>
                @*<a class="link-dark" asp-page="CreateCourse">Create New Course</a>*@
            </p>
            <form>
                <p class="text-dark">
                    <input class="textField" type="text" placeholder="Search.." asp-for="FilterCriteria" />
                    <input type="submit" value="Filter" />
                </p>
            </form>
            <table class="table table-responsive p-3">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Courses)
                    {
                        <tr>
                            <td>
                                @*<a class="link-dark" asp-page="/Statistics/InputStats1" asp-route-id="@item.Key"> @item.Value.Name</a>*@
                                <form asp-page-handler="SelectCourse" method="post">
                                    <button class="btn btn-success w-100">@item.Value.Name</button>
                                    <input type="hidden" name="id" value="@item.Key" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    </div>