StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Statistics
{
    public class InputStats1Model : PageModel
    {
        private IStatistics statistics;
        private ICourses courses;

        [BindProperty]
        public StatSheet MockSheet { get; private set; }

        public int CurrentHoleId { get; private set; }

        public InputStats1Model(IStatistics statsRepo, ICourses courseRepo)
        {
            statistics = statsRepo;
            courses = courseRepo;

            // TO USE A SHEET THAT IS SAVED BETWEEN RESTARTING PROGRAM. DELETE ABOVE TO DO THIS^^
            MockSheet = statistics.GetSheet();

            CurrentHoleId = UserRepository.Instance.Get().CurrentHolesFilled;
        }

        public Course CurrentCourse { get; private set; }
        public Dictionary<int, Hole> Holes { get; private set; }

        public IActionResult OnGet()
        {
            CurrentCourse = courses.GetCourse(1);
            Holes = courses.AllHoles(1);
            statistics.UpdateSheet(MockSheet);

            return Page();
        }

        public IActionResult OnPostMissFairwayLeft()
        {
            MockSheet.FairWayMissLeft++;
            MockSheet.TotalFairwayStrokes++;
            statistics.UpdateSheet(MockSheet);

            return RedirectToPage("InputStats2");
        }
        public IActionResult OnPostHitFairway()
        {
            MockSheet.FairWayHit++;
            MockSheet.TotalFairwayStrokes++;
            statistics.UpdateSheet(MockSheet);

            return RedirectToPage("InputStats2");
        }
        public IActionResult OnPostMissFairwayRight()
        {
            MockSheet.FairWayMissRight++;
            MockSheet.TotalFairwayStrokes++;
            statistics.UpdateSheet(MockSheet);

            return RedirectToPage("InputStats2");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Statistics
{
    public class InputStats2Model : PageModel
    {
        private IStatistics statistics;
        private ICourses courses;

        [BindProperty]
        public StatSheet MyStatSheet { get; private set; }

        public int CurrentHoleId { get; private set; }

        public InputStats2Model(IStatistics statsRepo, ICourses courseRepo)
        {
            statistics = statsRepo;
            courses = courseRepo;

            MyStatSheet = statistics.GetSheet();

            CurrentHoleId = UserRepository.Instance.Get().CurrentHolesFilled;
        }

        public Course CurrentCourse { get; private set; }
        public Dictionary<int, Hole> Holes { get; private set; }

        public void OnGet()
        {
            CurrentCourse = courses.GetCourse(1);
            Holes = courses.AllHoles(1);
        }

        public IActionResult OnPostMissGreenLeft()
        {
            MyStatSheet.GreenMissLeft++;
            MyStatSheet.TotalGreenStrokes++;
            statistics.UpdateSheet(MyStatSheet);

            return RedirectToPage("InputStats3");
        }

        public IActionResult OnPostHitGreen()
        {
            MyStatSheet.GreenHit++;
            MyStatSheet.TotalGreenStrokes++;
            statistics.UpdateSheet(MyStatSheet);

            int id = UserRepository.Instance.Get().CurrentCourseId;
            if (courses.GetCourse(id).Holes.Count > UserRepository.Instance.Get().CurrentHolesFilled)
            {
                UserRepository.Instance.Get().CurrentHolesFilled++;

                // If the current holes par is more than 3, we go to the fairway. Otherwise, we skip the fairway shot.
                if (courses.GetCourse(id).Holes[UserRepository.Instance.Get().CurrentHolesFilled].Par > 3)
                    return RedirectToPage("InputStats1");
                else
                    return RedirectToPage("InputStats2");
            }
            else
            {
                return RedirectToPage("InputStats4");
            }
        }

        public IActionResult OnPostMissGreenRight()
        {
            MyStatSheet.GreenMissRight++;
            MyStatSheet.TotalGreenStrokes++;
            statistics.UpdateSheet(MyStatSheet);

            return RedirectToPage("InputStats3");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats3.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Statistics
{
    public class InputStats3Model : PageModel
    {
        private IStatistics statistics;
        private ICourses courses;

        [BindProperty]
        public StatSheet MyStatSheet { get; private set; }

        public int CurrentHoleId { get; private set; }

        public InputStats3Model(IStatistics statsRepo, ICourses courseRepo)
        {
            statistics = statsRepo;
            courses = courseRepo;

            MyStatSheet = statistics.GetSheet();

            CurrentHoleId = UserRepository.Instance.Get().CurrentHolesFilled;
        }

        public Course CurrentCourse { get; private set; }
        public Dictionary<int, Hole> Holes { get; private set; }

        public IActionResult OnGet()
        {
            CurrentCourse = courses.GetCourse(1);
            Holes = courses.AllHoles(1);

            return Page();
        }

        public IActionResult OnPostScrambleIn()
        {
            MyStatSheet.ScrambleHit++;
            MyStatSheet.TotalScrambleStrokes++;
            statistics.UpdateSheet(MyStatSheet);

            int id = UserRepository.Instance.Get().CurrentCourseId;
            if (courses.GetCourse(id).Holes.Count > UserRepository.Instance.Get().CurrentHolesFilled)
            {
                UserRepository.Instance.Get().CurrentHolesFilled++;

                // If the current holes par is more than 3, we go to the fairway. Otherwise, we skip the fairway shot.
                if (courses.GetCourse(id).Holes[UserRepository.Instance.Get().CurrentHolesFilled].Par > 3)
                    return RedirectToPage("InputStats1");
                else
                    return RedirectToPage("InputStats2");
            }
            else
            {
                return RedirectToPage("InputStats4");
            }
        }

        public IActionResult OnPostScrambleOut()
        {
            MyStatSheet.ScrambleMiss++;
            MyStatSheet.TotalScrambleStrokes++;
            statistics.UpdateSheet(MyStatSheet);

            int id = UserRepository.Instance.Get().CurrentCourseId;
            if (courses.GetCourse(id).Holes.Count > UserRepository.Instance.Get().CurrentHolesFilled)
            {
                UserRepository.Instance.Get().CurrentHolesFilled++;

                // If the current holes par is more than 3, we go to the fairway. Otherwise, we skip the fairway shot.
                if (courses.GetCourse(id).Holes[UserRepository.Instance.Get().CurrentHolesFilled].Par > 3)
                    return RedirectToPage("InputStats1");
                else
                    return RedirectToPage("InputStats2");
            }
            else
            {
                return RedirectToPage("InputStats4");
            }
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats4.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProtoWeb.Interfaces;
using ProtoWeb.Models;

namespace ProtoWeb.Pages.Statistics
{
    public class InputStats4Model : PageModel
    {
        private IStatistics statistics;
        private ICourses courses;

        [BindProperty]
        public StatSheet MyStatSheet { get; private set; }

        [BindProperty]
        public int TotalScoreValue { get; set; }

        public int CurrentHoleId { get; private set; }

        public InputStats4Model(IStatistics statsRepo, ICourses courseRepo)
        {
            statistics = statsRepo;
            courses = courseRepo;

            MyStatSheet = statistics.GetSheet();

            CurrentHoleId = UserRepository.Instance.Get().CurrentHolesFilled;
        }

        public Course CurrentCourse { get; private set; }
        public Dictionary<int, Hole> Holes { get; private set; }

        public IActionResult OnGet()
        {
            CurrentCourse = courses.GetCourse(1);
            Holes = courses.AllHoles(1);

            return Page();
        }

        public IActionResult OnPost()
        {
            CurrentCourse = courses.GetCourse(1);
            Holes = courses.AllHoles(1);

            return Page();
        }

        public IActionResult OnPostTotalScore()
        {
            MyStatSheet.TotalScore = TotalScoreValue;
            statistics.UpdateSheet(MyStatSheet);

            return RedirectToPage("../ShowResults");
        }
    }
}

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats1.cshtml
@page
@model ProtoWeb.Pages.Statistics.InputStats1Model
@{
    ViewData["Title"] = "InputStats1";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1> Hole @Model.CurrentHoleId</h1>
        <div class="img-fluid text-center">
            <img src="../img/hole_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <form method="post">
                <table class="text-center">
                    <tr>
                        <td colspan="3">Fairway</td>
                    </tr>
                    <tr>
                        <td>Left</td>
                        <td></td>
                        <td>Right</td>
                    </tr>
                    <tr>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet.FairWayMissLeft" asp-page-handler="MissFairwayLeft" type="submit" class="btn-danger btn-miss" value="Miss" />
                        </td>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet.FairWayHit" asp-page-handler="HitFairway" type="submit" class="btn-primary btn-hit" value="Hit" />
                        </td>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet.FairWayMissRight" asp-page-handler="MissFairwayRight" type="submit" class="btn-danger btn-miss" value="Miss" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <br />
        <div class="my-auto container frame">
            <p class="text-dark">
                Your Statistics:
            </p>
            <p class="text-dark">
                Fairway misses left: @Model.MyStatSheet.FairWayMissLeft
            </p>
            <p class="text-dark">
                Fairway hits: @Model.MyStatSheet.FairWayHit
            </p>
            <p class="text-dark">
                Fairway misses right: @Model.MyStatSheet.FairWayMissRight
            </p>
            <br />
            <p class="text-dark">
                Green misses left: @Model.MyStatSheet.GreenMissLeft
            </p>
            <p class="text-dark">
                Green hits: @Model.MyStatSheet.GreenHit
            </p>
            <p class="text-dark">
                Green misses right: @Model.MyStatSheet.GreenMissRight
            </p>
            <br />
            <p class="text-dark">
                Scramble outs: @Model.MyStatSheet.ScrambleMiss
            </p>
            <p class="text-dark">
                Scramble ins: @Model.MyStatSheet.ScrambleHit
            </p>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats2.cshtml
@page
@model ProtoWeb.Pages.Statistics.InputStats2Model
@{
    ViewData["Title"] = "InputStats2";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1> Hole @Model.CurrentHoleId</h1>
        <div class="img-fluid text-center">
            <img src="../img/hole_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <form method="post">
                <table class="text-center">
                    <tr>
                        <td colspan="3">Green</td>
                    </tr>
                    <tr>
                        <td>Left</td>
                        <td></td>
                        <td>Right</td>
                    </tr>
                    <tr>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet" asp-page-handler="MissGreenLeft" type="submit" class="btn-danger btn-miss" value="Miss" />
                        </td>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet" asp-page-handler="HitGreen" type="submit" class="btn-primary btn-hit" value="Hit" />
                        </td>
                        <td class="p-2">
                            <input asp-for="@Model.MyStatSheet" asp-page-handler="MissGreenRight" type="submit" class="btn-danger btn-miss" value="Miss" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <br />
        <div class="my-auto container frame">
            <p class="text-dark">
                Your Statistics:
            </p>
            <p class="text-dark">
                Fairway misses left: @Model.MyStatSheet.FairWayMissLeft
            </p>
            <p class="text-dark">
                Fairway hits: @Model.MyStatSheet.FairWayHit
            </p>
            <p class="text-dark">
                Fairway misses right: @Model.MyStatSheet.FairWayMissRight
            </p>
            <br />
            <p class="text-dark">
                Green misses left: @Model.MyStatSheet.GreenMissLeft
            </p>
            <p class="text-dark">
                Green hits: @Model.MyStatSheet.GreenHit
            </p>
            <p class="text-dark">
                Green misses right: @Model.MyStatSheet.GreenMissRight
            </p>
            <br />
            <p class="text-dark">
                Scramble outs: @Model.MyStatSheet.ScrambleMiss
            </p>
            <p class="text-dark">
                Scramble ins: @Model.MyStatSheet.ScrambleHit
            </p>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats3.cshtml
@page
@model ProtoWeb.Pages.Statistics.InputStats3Model
@{
    ViewData["Title"] = "InputStats3";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <h1> Hole @Model.CurrentHoleId</h1>
        <div class="img-fluid text-center">
            <img src="../img/hole_icon.png" height="120" />
        </div>
        <div class="my-auto container frame">
            <form method="post">
                <table class="text-center">
                    <tr>
                        <td colspan="3">Scramble</td>
                    </tr>
                    <tr>
                        <td>Out</td>
                        <td>In</td>
                    </tr>
                    <tr>
                        <td class="p-2">
                            <input asp-page-handler="ScrambleOut" type="submit" class="btn-danger btn-miss" value="Out" />
                        </td>
                        <td class="p-2">
                            <input asp-page-handler="ScrambleIn" type="submit" class="btn-primary btn-hit" value="In" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <br />
        <div class="my-auto container frame">
            <p class="text-dark">
                Your Statistics:
            </p>
            <p class="text-dark">
                Fairway misses left: @Model.MyStatSheet.FairWayMissLeft
            </p>
            <p class="text-dark">
                Fairway hits: @Model.MyStatSheet.FairWayHit
            </p>
            <p class="text-dark">
                Fairway misses right: @Model.MyStatSheet.FairWayMissRight
            </p>
            <br />
            <p class="text-dark">
                Green misses left: @Model.MyStatSheet.GreenMissLeft
            </p>
            <p class="text-dark">
                Green hits: @Model.MyStatSheet.GreenHit
            </p>
            <p class="text-dark">
                Green misses right: @Model.MyStatSheet.GreenMissRight
            </p>
            <br />
            <p class="text-dark">
                Scramble outs: @Model.MyStatSheet.ScrambleMiss
            </p>
            <p class="text-dark">
                Scramble ins: @Model.MyStatSheet.ScrambleHit
            </p>
        </div>
    </div>
</div>

StatsForeGolfers/ProtoWeb/Pages/Statistics/InputStats4.cshtml
@page
@model ProtoWeb.Pages.Statistics.InputStats4Model
@{
    ViewData["Title"] = "InputStats4";
}

<div class="row justify-content-center p-4">
    <div class="col-auto">
        <div class="form-check">
            <div class="container-fluid">
                <h4>Hole @Model.CurrentHoleId</h4>
            </div>
            <div class="img-fluid text-center">
                <img src="../img/course_icon.png" height="120" />
            </div>
            <form method="post">
                <div class="my-auto container frame">
                    <h5 class="text-dark">What is your Total Score?</h5>
                    <div style="padding-left: 1.25rem">
                        @*<h4 class="text-dark">Total Score</h4>*@
                        <input asp-for="@Model.TotalScoreValue" type="number" name="TotalScoreValue" class="form-check-input textField" value="Your Total Score" />
                        <label asp-for="@Model.TotalScoreValue" class="control-label">
                            Your Total Score
                        </label>
                        <span asp-validation-for="@Model.TotalScoreValue" class="text-danger"></span>

                        <div class="form-group pt-4">
                            <input type="submit" value="Create" class="btn btn-primary" asp-page-handler="TotalScore" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <br />
        <div class="my-auto container frame">
            <p class="text-dark">
                Your Statistics:
            </p>
            <p class="text-dark">
                Fairway misses left: @Model.MyStatSheet.FairWayMissLeft
            </p>
            <p class="text-dark">
                Fairway hits: @Model.MyStatSheet.FairWayHit
            </p>
            <p class="text-dark">
                Fairway misses right: @Model.MyStatSheet.FairWayMissRight
            </p>
            <br />
            <p class="text-dark">
                Green misses left: @Model.MyStatSheet.GreenMissLeft
            </p>
            <p class="text-dark">
                Green hits: @Model.MyStatSheet.GreenHit
            </p>
            <p class="text-dark">
                Green misses right: @Model.MyStatSheet.GreenMissRight
            </p>
            <br />
            <p class="text-dark">
                Scramble outs: @Model.MyStatSheet.ScrambleMiss
            </p>
            <p class="text-dark">
                Scramble ins: @Model.MyStatSheet.ScrambleHit
            </p>
        </div>
    </div>
</div>